services:
  spdx:
    container_name: spdx_dev
    image: spdx-dev:latest
    build:
      context: ./
      dockerfile: dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./:/spdx
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/spdx/src
      - SPDX_REDIS_HOST=redis
      - SPDXParser.LocalLicensesDir=/licenses/current
      - SPDXParser.OnlyUseLocalLicenses=true
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:5.0-alpine
    container_name: redis
    restart: always
    volumes:
      - data-volume:/data
    ports:
      - 6379:6379

volumes:
  data-volume:
